name: nicecode flow     # 工作流名称

on:
  push:
    branches: ['main']      # 监听 main 分支的推送
    paths:
      - 'package.json'      # 仅当 package.json 发生变化时触发

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest         # 运行环境
    steps:
      - uses: actions/checkout@v4   # 检出代码仓库
        with:
          fetch-depth: 2            # 获取最近两个提交的历史记录

      - name: 检查 package.json 的版本变化
        id: check_version
        run: |
          git diff HEAD~1 HEAD -- package.json > version.diff
          if [ -s version.diff ]; then
            old_version=$(git show HEAD~1:package.json | jq -r '.version')
            new_version=$(cat package.json | jq -r '.version')
            echo "old_version=$old_version" >> $GITHUB_OUTPUT
            echo "new_version=$new_version" >> $GITHUB_OUTPUT
          else
            echo "package.json 未发生变化，退出。"
            exit 1
          fi

      - name: 判断版本是否更新
        if: ${{ steps.check_version.outputs.old_version == steps.check_version.outputs.new_version }}
        run: |
          echo "package.json 的 version 未发生变化，退出。"
          exit 1

      - uses: actions/setup-node@v3
        with:
          node-version: 20                  # Node.js 版本
          registry-url: https://registry.npmjs.org

      - name: 设置 pnpm                     # 安装 pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
              
      - run: pnpm install                    # 安装项目依赖

      - run: pnpm run bp                     # 运行构建和发布脚本
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # 使用 npm 令牌进行发布